### ISSUE TITLE
Downloadable build?

### ISSUE THREAD

**Issue by treboR-0** [xforce/jc3-handling-editor#6]
Good add-on I look forward to its server side implementation in JC3MP until then could you make a complete download package, including instructions, available for those of us that can't assemble this.

**Comment by xforce** [comment]
Once I get it to a point where it makes sense, yes of course. I want to add the functionality first, I made it open very early so most of the things are still missing, but it should be done soon.

**Comment by treboR-0** [comment]
I presumed it was ready for use. Thanks again for hearing my 2 years of asking for exactly this mod. So far it looks like exactly what the beautiful drift roads, wild 4x4 terrain, and airport drag strips of Medici are looking for. If you need any alpha feedback I've written thousands of handles for SA, IV, V, Unreal and Unity over the past 5 years. If I can be of assistance in estimating what your mod is and isn't doing as it should, don't hesitate to ask. I've been bouncing cars into the sky for years looking for perfection.

**Comment by treboR-0** [comment]
good lookin progress

**Comment by treboR-0** [comment]
no progress :-(

**Comment by xforce** [comment]
you can now find early alpha builds on the releases tab
